// Gallery Configuration
const galleryConfig = {
  title: "de Queiroz Family Trip to London & Paris - 2025",
  galleries: [
    {
      id: "london-gallery",
      name: "Days in London",
      photos: [
      { file: "london-1.jpg", title: "Rosetta Stone", description: "Lucas with the Rosetta Stone. The key that unlocked ancient Egyptian hieroglyphs, the Rosetta Stone is one of the Museum's most famous objects.",  group: "London" },
      { file: "london-1b.jpg", title: "Hoa Hakananai'a", description: "Hoa Hakananai'a at the British Museum. Hoa Hakananai'a, meaning lost or stolen friend in the Rapa Nui language, is a basalt moai statue from Easter Island (Rapa Nui) that is now housed in the British Museum. The statue was taken from the island by British sailors in 1868 and is considered a masterpiece of Easter Island sculpture. It is known for its unique carvings on the back, including low-relief designs and petroglyphs.",  group: "London" },
      { file: "london-2.jpg", title: "Bust of Ramesses the Great", description: "This colossal bust is of the Egyptian pharaoh Ramesses II, who reigned from 1279–1213 BC. Weighing an incredible 7.5 tonnes, the bust was once part of a larger statue which sat in the Ramesseum, a temple in Thebes (modern Luxor) built by the pharaoh. Its decoration celebrated his military achievements and his close association with the creator god Amun-Ra. The press coverage of the bust's transportation to the UK is believed to have inspired the poet Shelley's favourite sonnet, Ozymandias.",  group: "London" },
      { file: "london-3.jpg", title: "Lucas and Family with his cousin Ana Julia", description: "This picture shows Lucas and his family with his cousin Ana Julia, she lives in London and is two years older than Clara",  group: "London" },
      { file: "london-4.jpg", title: "Lucas and Family in front of the British Museum", description: "This picture shows Lucas, his mom Luana, his sister Clara, and his cousin Ana Julia in front of the British Museum. Lucas's dad Anderson took the photo.",  group: "London" },
      { file: "london-5.jpg", title: "London's Big Ben", description: "Big Ben is the nickname for the Great Bell of the Great Clock of Westminster, and, by extension, for the clock tower itself, which stands at the north end of the Palace of Westminster in London, England. Originally named the Clock Tower, it was renamed Elizabeth Tower in 2012 to mark the the Diamond Jubilee of Queen Elizabeth II. The clock is a striking clock with five bells.",  group: "London" },
      { file: "london-6.jpg", title: "Lucas, Luana, and Clara in front of the Buckingham Palace", description: "Buckingham Palace is a royal residence in London, and the administrative headquarters of the monarch of the United Kingdom. Located in the City of Westminster, the palace is often at the centre of state occasions and royal hospitality.",  group: "London" },
      { file: "london-7.jpg", title: "Buckingham Palace", description: "Watching the Changing of the Guard at Buckingham Palace",  group: "London" },
      { file: "london-8.jpg", title: "London's Big Ben ", description: "",  group: "London" },
      { file: "london-9.jpg", title: "London's Big Ben", description: "",  group: "London" },
      { file: "london-10.jpg", title: "Westminster Bridge", description: "", group: "London" },
      { file: "london-11.jpg", title: "London Bus", description: "", group: "London" },
      { file: "london-12.jpg", title: "Water-Lilies, Monet, London National Gallery", description: "", group: "London" },
      { file: "london-13.jpg", title: "The Water Lily Pond at the London National Galery", description: "The Water Lily Pond, also known as Les Nymphéas, is a series of paintings by Claude Monet, particularly famous for his depiction of the water lilies he cultivated in his garden at Giverny in France. Monet created a special pond for these flowers and the Japanese footbridge, and he spent years painting various versions of the scene, capturing the reflections and light on the water's surface.",  group: "London" },
      { file: "london-14.jpg", title: "Wheat Field with Cypresses, Van Gogh, London National Galery", description: "", group: "London" },
      { file: "london-15.jpg", title: "Fish and Chips at Poppies", description: "", group: "London" },
      { file: "london-16.jpg", title: "Famous Abbey Road Pedestrian Crossing from Beatles album Cover", description: "", group: "London" },
      { file: "london-17.jpg", title: "London Bridge View with Cousins Marcel and Vania", description: "", group: "London" },
      { file: "london-18.jpg", title: "London Bridge View", description: "", group: "London" },
      { file: "london-18b.jpg", title: "London Bridge a side Different View with my Family", description: "", group: "London" },
      { file: "london-19.jpg", title: "Tower Bridge", description: "", group: "London" },
      { file: "london-20.jpg", title: "Lucas and Family at the Convent Garden", description: "A shopping and entertainment hub in London's West End, Covent Garden centres on the elegant, car-free Piazza, home to fashion stores, craft stalls at the Apple Market, and the Royal Opera House. Street entertainers perform by 17th-century St. Paul's Church, and the London Transport Museum houses vintage vehicles. Great restaurants serve European cuisines, and nearby theatres draw crowds for plays and musicals.", group: "London" },
      ]
    },
    {
      id: "paris-gallery",
      name: "Days in Paris",
      photos: [
      { file: "paris-1.jpg", title: "Evening at Montmatre", description: "", group: "Paris" },
      { file: "paris-2.jpg", title: "Tuleries Garden Fountain", description: "", group: "Paris" },
      { file: "paris-3b.jpg", title: "Waiting to Go up, the Eiffel Tower", description: "", group: "Paris" },
      { file: "paris-3c.jpg", title: "Paris, a View from Above", description: "", group: "Paris" },
      { file: "paris-3.jpg", title: "Lucas and Clara holding Eiffel Tower lighting time", description: "", group: "Paris" },
      { file: "paris-4.jpg", title: "Eiffel Tower", description: "", group: "Paris" },
      { file: "paris-4b.jpg", title: "Watching the sunset from Champs de Mars", description: "", group: "Paris" },
      { file: "paris-4c.jpg", title: "Watching the sunset from Champs de Mars", description: "", group: "Paris" },
      { file: "paris-5.jpg", title: "One of the Amazing Bakeries we stopped to eat", description: "", group: "Paris" },
      { file: "paris-7.jpg", title: "Lucas and Clara enjoying Eiffel Tower", description: "", group: "Paris" },
      { file: "paris-9.jpg", title: "Palace of Versailles", description: "", group: "Paris" },
      { file: "paris-9a.jpg", title: "Palace of Versailles Garden", description: "", group: "Paris" },
      { file: "paris-9b.jpg", title: "Palace of Versailles Garden", description: "", group: "Paris" },
      { file: "paris-9c.jpg", title: "Palace of Versailles Garden", description: "", group: "Paris" },
      { file: "paris-10.jpg", title: "Palace of Versailles Garden with my Family", description: "", group: "Paris" },
      { file: "paris-11.jpg", title: "Notre-Dame Cathedral", description: "", group: "Paris" },
      { file: "paris-12.jpg", title: "Sacre-Coeur Basilica", description: "", group: "Paris" },
      { file: "paris-12b.jpg", title: "All the locks in front of Sacre-Coeur", description: "", group: "Paris" },
      { file: "paris-12c.jpg", title: "View from Sacre-Coeur Basilica", description: "", group: "Paris" },
      { file: "paris-13.jpg", title: "The Tuileries Garden outside the Louvre Museum", description: "", group: "Paris" },
      { file: "paris-14.jpg", title: "Place de la Concorde", description: "", group: "Paris" },
      { file: "paris-15.jpg", title: "The Pantheon", description: "The Pantheon in Paris is a landmark neoclassical building that serves as a mausoleum and the final resting place for many of France's most celebrated figures, including Voltaire, Rousseau, Victor Hugo, and Marie Curie", group: "Paris" },
      { file: "paris-17.jpg", title: "The Arc de Triomphe", description: "", group: "Paris" },
      { file: "paris-18.jpg", title: "Visiting the Louvre Musuem", description: "", group: "Paris" },
      { file: "paris-19.jpg", title: "Lucas with Monalisa", description: "", group: "Paris" },
      { file: "paris-19b.jpg", title: "A Closer look at Monalisa", description: "The Mona Lisa is a half-length portrait painting by Italian artist Leonardo da Vinci, considered one of the most famous works of art in the world. The painting depicts Lisa Gherardini, the wife of Francesco del Giocondo, a Florentine silk merchant, and is known for her enigmatic smile and use of sfumato (a technique that creates a smoky, soft effect). ", group: "Paris" },
      { file: "paris-20.jpg", title: "Inside The Louvre Museum", description: "", group: "Paris" },
      { file: "paris-21.jpg", title: "Lucas looking at Venus de Milo", description: "The Venus de Milo, also known as the Aphrodite of Milos, is a famous Greek sculpture representing the goddess of love and beauty. It's a marble statue believed to have been created around 130-100 BC during the Hellenistic period. The statue was discovered on the Greek island of Milos in 1820 and is now housed at the Louvre Museum in Paris. ", group: "Paris" },
      { file: "paris-22.jpg", title: "Winged Victory of Samothrace", description: "The Winged Victory of Samothrace, or the Niké of Samothrace, is a votive monument originally discovered on the island of Samothrace in the northeastern Aegean Sea. It is a masterpiece of Greek sculpture from the Hellenistic era, dating from the beginning of the 2nd century BC.", group: "Paris" },
      ]
    }
  ]
}; 